= CoTC & Mobile Dev joint project
:toc:
:toclevels: 2

== Overview

The repository submodules are reflective of the architecture shown in the image. The uploader queue is preliminarily implemented using NATS. The submodules are as follows:

* link:https://github.com/mikeyfennelly1/ise--+y2+--+b3+--+project+--collector[Collector Agent]: The `ise--+y2+--+b3+--+project+--collector` submodule corresponds to the `Collector Agent` in the diagram.
* link:https://github.com/mikeyfennelly1/ise--+y2+--+b3+--+project+--desktop-sysinfo[Device 1]: The `ise--+y2+--+b3+--+project+--desktop-sysinfo` submodule corresponds to `Device 1` in the diagram.
* link:https://github.com/mikeyfennelly1/ise--+y2+--+b3+--+project+--mobile-app[Mobile Data (Firebase)]: The `ise--+y2+--+b3+--+project+--mobile-app` submodule corresponds to `Mobile Data (Firebase)` in the diagram. Although the `Mobile Data (Firebase)` labelling in the provided reference architecture does not include the mobile app, the provided and corresponding `mobile-app` submodule accounts for both the android source code for the mobile app and any firebase related scripts/configurations.

== Getting Started
This project utilizes Git submodules. To ensure all components are correctly initialized, clone the repository using:
----
git clone --recurse-submodules git@github.com:mikeyfennelly1/ise--y2--b3--project.git
----
If you have already cloned the repository without `--recurse-submodules`, you can initialize them by running:
----
git submodule update --init --recursive
----

== Running the Applications
=== Prerequisites
1. tmux
2. Go
3. Java 21
4. Gradle
5. Project directories installed

=== Local Development
Run the following command:

[source, bash]
----
chmod +x ./start.sh
./start.sh
----

== Submodule Version Control & Releases
Each project is packaged in a docker container, whose version is consistent with the release tag of the repository For example:

|===
| Codebase version for submodule | Corresponding docker image

| `v1.0.2`
| `mikeyfennelly/<image-name>:v1.0.2`
|===

There must be a 1:1 mapping of repository tag to docker image, where for each repository tag, the corresponding image is the true docker artifact for that source code.

== Deployment management

The configuration for our deployment on our VM is managed in the top-level repository.
