# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  docker:release:dev:
    desc: Build all container artifacts and release dev timestamp images
    cmds:
      - ./libcotc/build.sh
      - ./cotcsubscriber/scripts/docker-build.sh
      - ./cotccollector/scripts/docker-build.sh
    silent: false

  deploy:latest:
    desc: Deploy the latest configuration for the application.
    cmds:
      - ansible-playbook .ansible/deploy.yml -i .ansible/inventory.ini --vault-password-file ./.vault_pass
    silent: false

  deploy:latest:verbose:
    desc: Deploy the latest configuration for the application in verbose mode.
    cmds:
      - ansible-playbook .ansible/deploy.yml -i .ansible/inventory.ini -vvv --vault-password-file ./.vault_pass
    silent: false


  nginx:
    desc: Start nginx
    cmds:
      - chmod +x ./scripts/nginx.sh
      - sudo ./scripts/nginx.sh start
    silent: true
  top:
    desc: See dashboard of durable consumers to the JetStream queue.
    cmds:
      - nats-top
    silent: true

  test:e2e:local:
    desc: "Run REST API tests against localhost:8082. Filter by name: task test:subscriber -- --test-name-pattern='<pattern>'"
    cmds:
      - node --test --test-reporter=spec {{.CLI_ARGS}} ./test/test.js
    silent: false

  test:local:report:
    desc: Run REST API tests and generate report.json + report.html in test/
    cmds:
      - node --test --test-reporter=./test/reporter.js {{.CLI_ARGS}} ./test/test.js
    silent: false

  test:report:
    desc: Generate test reports
    cmds:
      - node ./test/generate-html.js

  test:e2e:prod:
    desc: "Run REST API tests against localhost:8082. Filter by name: task test:subscriber -- --test-name-pattern='<pattern>'"
    cmds:
      - node --test {{.CLI_ARGS}} ./test/test.js
    silent: false

  test:local:verbose:
    desc: "Run REST API tests against localhost:8082. Filter by name: task test:subscriber -- --test-name-pattern='<pattern>'"
    cmds:
      - node --test {{.CLI_ARGS}} ./test/test.js
    silent: false
