apiVersion: v1
kind: Service
metadata:
  name: {{ include "cotc.gatewayServiceName" . }}
  labels:
    {{- include "cotc.labels" . | nindent 4 }}
    {{- include "cotc.selectorLabels" (dict "root" . "component" "api-gateway") | nindent 4 }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  selector:
    {{- include "cotc.selectorLabels" (dict "root" . "component" "api-gateway") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.apiGateway.port }}
      targetPort: http
      {{- if and (eq .Values.apiGateway.service.type "NodePort") .Values.apiGateway.service.nodePort }}
      nodePort: {{ .Values.apiGateway.service.nodePort }}
      {{- end }}
