apiVersion: v1
kind: Service
metadata:
  name: {{ include "cotc.collectorServiceName" . }}
  labels:
    {{- include "cotc.labels" . | nindent 4 }}
    {{- include "cotc.selectorLabels" (dict "root" . "component" "cotccollector") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "cotc.selectorLabels" (dict "root" . "component" "cotccollector") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.cotccollector.port }}
      targetPort: http
