apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cotc.fullname" . }}-db-pvc
  labels:
    {{- include "cotc.labels" . | nindent 4 }}
    {{- include "cotc.selectorLabels" (dict "root" . "component" "db") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
  {{- if .Values.postgres.storageClassName }}
  storageClassName: {{ .Values.postgres.storageClassName }}
  {{- end }}
