---
# PostgreSQL credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cotc.fullname" . }}-db-secret
  labels:
    {{- include "cotc.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
---
# Google service account credentials for cotcsubscriber
{{- if .Values.cotcsubscriber.googleServiceAccountJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cotc.fullname" . }}-google-sa
  labels:
    {{- include "cotc.labels" . | nindent 4 }}
type: Opaque
data:
  serviceAccount.json: {{ .Values.cotcsubscriber.googleServiceAccountJson }}
{{- end }}
