app_name: ise--y2--b3--project
nginx_port: 8080
repo_ssh_url: git@github.com:mikeyfennelly1/ise--y2--b3--project.git
gh_pull_key_file: /home/mfennelly/.ssh/ansible_github_pull_key
repo_pull_dest: /srv/app